services:
  db:
    image: 'postgres:16'
    ports:
      - '${POSTGRES_PORT:-8400}:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-local}
      - POSTGRES_USER=${POSTGRES_USER:-local}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-local}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 50m
    stdin_open: true
    command: postgres -c 'max_connections=300' -c 'lock_timeout=2000ms'